# Generated by Django 5.2 on 2025-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.AddField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
